### ISSUE TITLE
dhara_nand_is_free returns true at I/O error

### ISSUE THREAD

**Issue by traffael** [aloebs29/flash_management#1]
Thanks for the nice use case of the dhara library, it was really helpful!

Found a small bug here:

https://github.com/aloebs29/flash_management/blob/fcd5c533b9a14afd4b84f954e5ac8a2556997f88/src/dhara/nand.c#L84

This line should be is_free = false;

**Comment by aloebs29** [comment]
I'm happy to hear it was helpful! Thanks for catching the error. Updated.
